# Use the latest 2.1 version of CircleCI pipeline processing engine, see https://circleci.com/docs/2.0/configuration-reference/
version: 2.1
  
jobs:
 build:
  working_directory: /todo-server
  docker:
   - image: circleci/golang:1.11
    environment:
    GO111MODULE: "on"
  steps:
   - checkout
   - restore_cache:
    key: go-module-cache-v1-{{ checksum "go.mod" }}

   - run: go mod download

   - save_cache:
    key: go-module-cache-v1-{{ checksum "go.mod" }}
    paths:
     - /go/pkg/mod/cache

   - run:
    name: start server
    command:  go run src/server.go 
    background: true

   - run:
    name: run test
    command: |
     sleep 5
     go test todo-server/src/ 